services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    repo: https://github.com/your-username/your-repo-name
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:YOUR_GENERATED_APP_KEY
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: database/database.sqlite
    startCommand: |
      php artisan config:clear
      php artisan cache:clear
      php artisan migrate --force
      php artisan serve --host=0.0.0.0 --port=10000
